/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface TagTernaryGraph {
      'aHex': string;
      'abAxisLabel': string;
      'abFadeName': string;
      'abFadeURL': string;
      'abMixHex': string;
      'abMixOpacity': string;
      'abTextPathHref': string;
      'abTextPathName': string;
      'acAxisLabel': string;
      'acTextPathHref': string;
      'acTextPathName': string;
      'axisLabelFontSize': number;
      'bHex': string;
      'bcAxisLabel': string;
      'bcTextPathHref': string;
      'bcTextPathName': string;
      'cFadeEndHex': string;
      'cFadeEndOpacity': string;
      'cFadeName': string;
      'cFadeURL': string;
      'cHex': string;
      'circleRadius': number;
      'corners': {"A":{"X","Y"}, "B":{"X","Y"},"C":{"X","Y"}};
      'plotArray': Array<{"X","Y","Label"}>;
      'recordArray': Array<{"A","B","C","Label"}>;
    }
  }

  interface HTMLTagTernaryGraphElement extends StencilComponents.TagTernaryGraph, HTMLStencilElement {}

  var HTMLTagTernaryGraphElement: {
    prototype: HTMLTagTernaryGraphElement;
    new (): HTMLTagTernaryGraphElement;
  };
  interface HTMLElementTagNameMap {
    'tag-ternary-graph': HTMLTagTernaryGraphElement;
  }
  interface ElementTagNameMap {
    'tag-ternary-graph': HTMLTagTernaryGraphElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'tag-ternary-graph': JSXElements.TagTernaryGraphAttributes;
    }
  }
  namespace JSXElements {
    export interface TagTernaryGraphAttributes extends HTMLAttributes {
      'aHex'?: string;
      'abAxisLabel'?: string;
      'abFadeName'?: string;
      'abFadeURL'?: string;
      'abMixHex'?: string;
      'abMixOpacity'?: string;
      'abTextPathHref'?: string;
      'abTextPathName'?: string;
      'acAxisLabel'?: string;
      'acTextPathHref'?: string;
      'acTextPathName'?: string;
      'axisLabelFontSize'?: number;
      'bHex'?: string;
      'bcAxisLabel'?: string;
      'bcTextPathHref'?: string;
      'bcTextPathName'?: string;
      'cFadeEndHex'?: string;
      'cFadeEndOpacity'?: string;
      'cFadeName'?: string;
      'cFadeURL'?: string;
      'cHex'?: string;
      'circleRadius'?: number;
      'corners'?: {"A":{"X","Y"}, "B":{"X","Y"},"C":{"X","Y"}};
      'plotArray'?: Array<{"X","Y","Label"}>;
      'recordArray'?: Array<{"A","B","C","Label"}>;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;